# Generated by Django 5.0.1 on 2024-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="community/avatar",
                verbose_name="Аватар сообщества",
            ),
        ),
    ]
