# Generated by Django 5.0.1 on 2024-02-09 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0002_alter_community_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="communities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
    ]
