# Generated by Django 5.0.1 on 2024-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=35, verbose_name="Название группы"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=35, unique=True, verbose_name="Псевдоним группы"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание группы"),
                ),
            ],
            options={
                "verbose_name": ("Группа",),
                "verbose_name_plural": ("Группы",),
                "ordering": ["slug"],
            },
        ),
    ]
