# Generated by Django 5.0.1 on 2024-02-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_age_user_avatar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendship",
            old_name="friends",
            new_name="users",
        ),
        migrations.AddField(
            model_name="friendship",
            name="current_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
