# Generated by Django 5.0.1 on 2024-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_age_user_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friends",
        ),
    ]
