# Generated by Django 5.0.1 on 2024-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_group_options_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user/avatar"),
        ),
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True, max_length=150, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.TextField(
                blank=True,
                choices=[("Парень", "Парень"), ("Девушка", "Девушка")],
                verbose_name="Пол",
            ),
        ),
    ]
