# Generated by Django 5.0.1 on 2024-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_avatar_user_biography_user_birth_date_user_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user/avatar",
                verbose_name="Аватар пользователя",
            ),
        ),
    ]
