# Generated by Django 5.0.2 on 2024-03-14 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="sex",
            new_name="gender",
        ),
    ]
