# Generated by Django 5.0.1 on 2024-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_user_age_group_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Описание группы"
            ),
        ),
    ]
