# Generated by Django 5.0.1 on 2024-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_group_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Возраст"),
        ),
    ]
