# Generated by Django 5.0.1 on 2024-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_community_delete_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Community",
        ),
    ]
