# Generated by Django 5.0.1 on 2024-01-31 12:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_friend_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="friends_from",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 31, 12, 57, 48, 40743, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
