# Generated by Django 5.0.1 on 2024-01-31 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_friend_friends_from"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friend",
            new_name="Friendship",
        ),
        migrations.AlterModelOptions(
            name="friendrequest",
            options={
                "ordering": ["sent_on"],
                "verbose_name": "Запрос дружбы",
                "verbose_name_plural": "Запросы дружбы",
            },
        ),
        migrations.AlterModelOptions(
            name="friendship",
            options={
                "ordering": ["friends_from"],
                "verbose_name": "Друг",
                "verbose_name_plural": "Друзья",
            },
        ),
    ]
