# Generated by Django 5.0.1 on 2024-02-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0002_alter_community_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текста поста")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="posts/image",
                        verbose_name="Картинка в посте",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор поста",
                    ),
                ),
                (
                    "communities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="communities",
                        to="communities.community",
                        verbose_name="Сообщества, куда был послан пост",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
            ],
        ),
    ]
