# Generated by Django 5.0.1 on 2024-02-09 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0003_alter_community_creator_alter_community_followers"),
        ("posts", "0002_alter_post_options_post_publish_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор поста",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="communities",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="posts",
                to="communities.community",
                verbose_name="Сообщества, куда отправили пост",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/image",
                verbose_name="Картинка в посте",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст поста"),
        ),
    ]
