# Generated by Django 5.0.1 on 2024-02-12 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0003_alter_community_creator_alter_community_followers"),
        ("posts", "0003_alter_post_author_alter_post_communities_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="communities",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="communities.community",
                verbose_name="Сообщества, куда отправили пост",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
